version: '3'
services:
  react:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  express:
    build:
      context: ./server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=Slink_db
      - DB_USER=postgres
      - DB_PASSWORD=1412
    ports:
      - "5555:5555"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=1412
      - POSTGRES_DB=Slink_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork: {}
