CREATE TABLE users (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL);

CREATE TABLE links (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id INT REFERENCES users (id),
  original_url TEXT NOT NULL,
  short_url TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
